name: Build Vitruvian ISO

on: [push]

jobs:
  iso-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies (host only)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            debootstrap debhelper \
            grub-efi-amd64-bin grub-pc-bin \
            mtools squashfs-tools xorriso \
            fakeroot devscripts lintian wget

      - name: Configure git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Create build directory
        run: mkdir -p generated.x86

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Bootstrap Trixie chroot
        run: cd generated.x86 && export TERM=xterm-256color && ../build/scripts/setupenv.sh

      - name: Run full build inside chroot
        run: |
            CHROOT="$GITHUB_WORKSPACE/generated.x86/LIVE_BOOT/chroot"
            mkdir -p "$CHROOT"
            sudo chroot "$CHROOT" /bin/bash -c "
            set -e
            mkdir -p buildtools generated.x86
            cd buildtools
            cmake -DBUILDTOOLS_MODE=1 .. -GNinja
            ninja
            cd ../generated.x86
            ../configure
            ninja
            cpack
            ../build/scripts/mkiso.sh
          "

      # Generate checksums for ISO
      - name: Generate ISO checksum
        run: |
          cd generated.x86/LIVE_BOOT
          for iso in *.iso; do
            sha256sum "$iso" > "$iso.sha256"
          done

      - name: Upload Vitruvian ISO
        uses: actions/upload-artifact@v4
        with:
          name: Vitruvian-ISO
          path: |
            generated.x86/LIVE_BOOT/*.iso
            generated.x86/LIVE_BOOT/*.sha256

      - name: Generate DEB checksums
        run: |
          cd generated.x86
          for deb in *.deb; do
            sha256sum "$deb" > "$deb.sha256"
          done

      - name: Upload Vitruvian DEB packages
        uses: actions/upload-artifact@v4
        with:
          name: Vitruvian-DEB
          path: |
            generated.x86/*.deb
            generated.x86/*.sha256
            
