name: Build Vitruvian ISO

on: [push]

jobs:
  iso-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install host build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            debootstrap debhelper \
            grub-efi-amd64-bin grub-pc-bin \
            mtools squashfs-tools xorriso \
            fakeroot devscripts lintian wget \
            linux-headers-$(uname -r)

      - name: Configure git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Create build directory
        run: mkdir -p generated.x86

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Bootstrap Trixie chroot
        run: cd generated.x86 && export TERM=xterm-256color && ../build/scripts/setupenv.sh

      - name: Build inside chroot (everything except kernel modules)
        run: |
          CHROOT="$GITHUB_WORKSPACE/generated.x86/LIVE_BOOT/chroot"
          sudo mkdir -p "$CHROOT/root/Vitruvian"
          sudo mount --bind "$GITHUB_WORKSPACE" "$CHROOT/root/Vitruvian"

          sudo chroot "$CHROOT" /bin/bash -c "
            set -e
            cd /root/Vitruvian
            mkdir -p buildtools generated.x86
            cd buildtools
            cmake -DBUILDTOOLS_MODE=1 .. -GNinja
            ninja
            cd ../generated.x86
            ../configure \
              -DCMAKE_SYSROOT=/ \
              -DCMAKE_FIND_ROOT_PATH=/ \
              -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
              -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
              -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
            ninja
            cpack
            ../build/scripts/mkiso.sh
          "

          sudo umount "$CHROOT/root/Vitruvian"

      - name: Compile kernel modules on host
        run: |
          cd $GITHUB_WORKSPACE/generated.x86/src/system/kernel/nexus/nexus
          make KDIR=/lib/modules/$(uname -r)/build M=$PWD MO=$PWD/build/ src=$PWD modules

      - name: Generate ISO checksum
        run: |
          cd generated.x86/LIVE_BOOT
          for iso in *.iso; do
            sha256sum "$iso" > "$iso.sha256"
          done

      - name: Upload Vitruvian ISO
        uses: actions/upload-artifact@v4
        with:
          name: Vitruvian-ISO
          path: |
            generated.x86/LIVE_BOOT/*.iso
            generated.x86/LIVE_BOOT/*.sha256

      - name: Generate DEB checksums
        run: |
          cd generated.x86
          for deb in *.deb; do
            sha256sum "$deb" > "$deb.sha256"
          done

      - name: Upload Vitruvian DEB packages
        uses: actions/upload-artifact@v4
        with:
          name: Vitruvian-DEB
          path: |
            generated.x86/*.deb
            generated.x86/*.sha256
            
