name: Build Vitruvian ISO

on: [push]

jobs:
  iso-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure git safe.directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Create build directory
        run: mkdir -p generated.x86

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Bootstrap Trixie chroot
        run: |
          cd generated.x86
          export TERM=xterm-256color
          ../build/scripts/setupenv.sh

      - name: Install dependencies inside chroot
        run: |
          CHROOT="$GITHUB_WORKSPACE/generated.x86/LIVE_BOOT/chroot"
          sudo chroot "$CHROOT" /bin/bash -c "
            apt-get update
            apt-get install -y --no-install-recommends \
              build-essential cmake ninja-build flex bison \
              libelf-dev libdrm-dev libfreetype-dev libgif-dev \
              libicns-dev libicu-dev libinput-dev libjpeg-dev \
              libncurses-dev libopenexr-dev libpng-dev libtiff-dev \
              libudev-dev libwebp-dev mtools squashfs-tools xorriso wget curl vim-tiny
          "

      - name: Install kernel headers inside chroot
        run: |
          CHROOT="$GITHUB_WORKSPACE/generated.x86/LIVE_BOOT/chroot"
          sudo chroot "$CHROOT" /bin/bash -c "
            KERNEL_VERSION=\$(uname -r)
            apt-get update
            apt-get install -y linux-headers-\$KERNEL_VERSION || echo 'Kernel headers not found, skipping'
          "

      - name: Bind repository and build inside chroot
        run: |
          CHROOT="$GITHUB_WORKSPACE/generated.x86/LIVE_BOOT/chroot"
          sudo mkdir -p "$CHROOT/root/Vitruvian"
          sudo mount --bind "$GITHUB_WORKSPACE" "$CHROOT/root/Vitruvian"
          sudo chroot "$CHROOT" /bin/bash -c "
            set -e
            cd /root/Vitruvian

            # Build buildtools
            mkdir -p buildtools
            cd buildtools
            cmake -DBUILDTOOLS_MODE=1 .. -GNinja
            ninja

            # Build Vitruvian in generated.x86
            cd ../generated.x86
            ../configure \
              -DCMAKE_SYSROOT=/ \
              -DCMAKE_FIND_ROOT_PATH=/ \
              -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY \
              -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
              -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
            ninja
            cpack
            ../build/scripts/mkiso.sh
          "
          sudo umount "$CHROOT/root/Vitruvian"

      - name: Upload ISO and DEB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vitruvian-Build
          path: |
            generated.x86/LIVE_BOOT/*.iso
            generated.x86/LIVE_BOOT/*.sha256
            generated.x86/*.deb
            generated.x86/*.sha256
            
